#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$kernel = new Kernel('dev', true);
$application = new Application($kernel);
$application->run();
