[supervisord]
nodaemon=true
logfile=/app/storage/supervisord.log
pidfile=/var/run/supervisord.pid

[program:bot]
command=php /app/console app:run
directory=/app
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:web]
command=php -S 0.0.0.0:8080 -t /app/public /app/public/index.php
directory=/app
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2
